import { write, plan } from "./lib.mjs";
const pct = (offerings, tier, p, fixed, note) => ({ offerings: [].concat(offerings), tier, spec: {}, rates: [{ name: "percentage of transaction", amount: p, unit: "percent" }, ...(fixed !== undefined ? [{ name: "fixed fee per transaction", amount: fixed, unit: "fixed" }] : [])], ...(note ? { note } : {}) });

write("stripe", [pct("payments:stripe:payments", "Cards (domestic)", 2.9, 0.3, "Per successful transaction. International cards, currency conversion and other methods cost more; ACH direct debit 0.8% capped at $5.")], { notes: "Billing (0.7% of billed volume) and Connect pricing separate." });
write("lemon-squeezy", [pct("payments:lemon-squeezy:merchant-of-record", "Merchant of record", 5, 0.5, "5% + 50¢ per transaction; Lemon Squeezy is the merchant of record (handles sales tax/VAT).")]);
write("square", [plan("payments:square:payments", "Square Free", 0, "month"), plan("payments:square:payments", "Square Plus", 49, "month"), plan("payments:square:payments", "Square Premium", 149, "month")], { notes: "Retail POS subscription prices as shown; per-transaction card rates not captured." });
write("cashfree", [plan("payments:cashfree:payments", "Platform fee (auto-debit < ₹1000)", null, "month", { note: "Fees in INR: platform fee ₹20 shown for one method, ₹7.5 + ₹7.5 for others; card rates around 1.95%-2.0% (method labels not captured)." , contact: true })], { currency: "INR", notes: "Method-level rate table not parsed reliably; not exported as prices." });
write("phonepe", [], { notes: "Scrape returned no prices." });
write("mux", [plan("media:mux:video", "Launch", 20, "month", { note: "$20/mo for $100 in usage credit; Free plan has $20 monthly usage credit." }), plan("media:mux:video", "Scale", 500, "month", { note: "$500/mo for $1,000 in usage credit." })], { notes: "Storage from $0.0024/min; delivery/encoding rates per resolution tier not captured." });
write("mapbox", [], { notes: "Rates are in per-API tier tables (map loads, geocoding, directions) with free-tier rows; not parsed reliably." });
write("here", [plan("maps:here:platform", "Vector tile requests (30,001 - 5M)", null, "1k-requests", { rates: [["per 1,000 transactions", 0.07, "1k-requests"]], note: "In EUR: €0.070 per 1,000 (30,001 to 5M), €0.056 (5M-10M)." })], { currency: "EUR", notes: "Advanced vector €0.191, raster €0.095, advanced raster €0.191 per 1,000 in the same first band." });
write("maptiler", [plan("maps:maptiler:cloud", "Free", 0, "month"), plan("maps:maptiler:cloud", "Pay as you go (flex)", 30, "month", { note: "Extra sessions $2.50 per 1k; 3D sessions $6.00 per 1k." })]);
write("livekit", [plan("rtc:livekit:cloud", "Build", 0, "month"), plan("rtc:livekit:cloud", "Ship", 50, "month", { note: "'Starting at'." }), plan("rtc:livekit:cloud", "Scale", 500, "month", { note: "'Starting at'." }), plan("rtc:livekit:cloud", "Agent session", null, "minute", { rates: [["agent session", 0.01, "minute"]] })]);
write("daily", [], { notes: "Scrape returned no content." });
