// Where each provider's prices live. One entry = one pricing page that gets scraped (1 Firecrawl credit each).
// Providers priced from a free API (AWS, Azure, Akamai/Linode, Vultr) are not here; see the adapters.
// "free" = open-source software with no licence fee: the cost is the server it runs on.
const P = (...u) => u;
export const SOURCES = {
  // --- Google Cloud (its Billing Catalog API needs a key, so these are scraped)
  "google-cloud": P(
    "https://cloud.google.com/compute/all-pricing", "https://cloud.google.com/run/pricing", "https://cloud.google.com/functions/pricing", "https://cloud.google.com/appengine/pricing",
    "https://cloud.google.com/kubernetes-engine/pricing", "https://cloud.google.com/sql/pricing", "https://cloud.google.com/alloydb/pricing", "https://cloud.google.com/firestore/pricing",
    "https://cloud.google.com/bigtable/pricing", "https://cloud.google.com/spanner/pricing", "https://cloud.google.com/memorystore/docs/redis/pricing", "https://cloud.google.com/storage/pricing",
    "https://cloud.google.com/compute/disks-image-pricing", "https://cloud.google.com/filestore/pricing", "https://cloud.google.com/vpc/network-pricing", "https://cloud.google.com/load-balancing/pricing",
    "https://cloud.google.com/cdn/pricing", "https://cloud.google.com/dns/pricing", "https://cloud.google.com/armor/pricing", "https://cloud.google.com/api-gateway/pricing",
    "https://cloud.google.com/tasks/pricing", "https://cloud.google.com/pubsub/pricing", "https://cloud.google.com/managed-service-for-apache-kafka/pricing", "https://cloud.google.com/composer/pricing",
    "https://cloud.google.com/bigquery/pricing", "https://cloud.google.com/dataproc/pricing", "https://cloud.google.com/dataflow/pricing", "https://cloud.google.com/data-fusion/pricing",
    "https://cloud.google.com/vertex-ai/pricing", "https://cloud.google.com/speech-to-text/pricing", "https://cloud.google.com/document-ai/pricing", "https://cloud.google.com/stackdriver/pricing",
    "https://cloud.google.com/secret-manager/pricing", "https://cloud.google.com/build/pricing", "https://cloud.google.com/artifact-registry/pricing", "https://cloud.google.com/scheduler/pricing",
    "https://cloud.google.com/transcoder/pricing", "https://cloud.google.com/datastream/pricing", "https://cloud.google.com/backup-disaster-recovery/pricing", "https://cloud.google.com/products/calculator/#tab=compute",
    "https://cloud.google.com/compute/vm-instance-pricing",
    "https://cloud.google.com/products/compute/pricing/general-purpose", "https://cloud.google.com/products/compute/pricing/compute-optimized", "https://cloud.google.com/products/compute/pricing/memory-optimized",
    "https://cloud.google.com/products/compute/pricing/network-optimized", "https://cloud.google.com/products/compute/pricing/storage-optimized", "https://cloud.google.com/products/compute/pricing/accelerator-optimized",
  ),
  // --- VPS / hosting
  hostinger: P("https://www.hostinger.com/vps-hosting"),
  digitalocean: P("https://www.digitalocean.com/pricing/droplets", "https://www.digitalocean.com/pricing/app-platform", "https://www.digitalocean.com/pricing/managed-databases", "https://www.digitalocean.com/pricing/kubernetes", "https://www.digitalocean.com/pricing/load-balancers", "https://www.digitalocean.com/pricing/volumes", "https://www.digitalocean.com/pricing/spaces-object-storage"),
  hetzner: P("https://docs.hetzner.com/general/infrastructure-and-availability/price-adjustment/", "https://www.hetzner.com/cloud/cost-optimized/", "https://www.hetzner.com/cloud/regular-performance/", "https://www.hetzner.com/cloud/general-purpose/", "https://www.hetzner.com/storage/object-storage/"),
  ovhcloud: P("https://www.ovhcloud.com/en/vps/", "https://www.ovhcloud.com/en/public-cloud/kubernetes/"),
  contabo: P("https://contabo.com/en/vps/"),
  scaleway: P("https://www.scaleway.com/en/pricing/?tags=compute", "https://www.scaleway.com/en/pricing/?tags=storage"),
  "oracle-cloud": P("https://www.oracle.com/cloud/compute/pricing/"),
  bluehost: P("https://www.bluehost.com/hosting/vps"),
  godaddy: P("https://www.godaddy.com/hosting/vps-hosting"),
  namecheap: P("https://www.namecheap.com/hosting/vps/"),
  ionos: P("https://www.ionos.com/servers/vps"),
  hostgator: P("https://www.hostgator.com/vps-hosting"),
  "a2-hosting": P("https://www.a2hosting.com/vps-hosting/"),
  "inmotion-hosting": P("https://www.inmotionhosting.com/vps-hosting"),
  "liquid-web": P("https://www.liquidweb.com/vps-hosting/"),
  kamatera: P("https://www.kamatera.com/pricing/"),
  cloudways: P("https://www.cloudways.com/en/pricing.php"),
  upcloud: P("https://upcloud.com/pricing"),
  "e2e-networks": P("https://www.e2enetworks.com/pricing"),
  "alibaba-cloud": P("https://www.alibabacloud.com/en/product/ecs-pricing-list/en"),
  "tencent-cloud": P("https://www.tencentcloud.com/products/cvm"),
  // --- serverless / PaaS / edge
  cloudflare: P("https://developers.cloudflare.com/workers/platform/pricing/", "https://www.cloudflare.com/plans/", "https://developers.cloudflare.com/kv/platform/pricing/", "https://developers.cloudflare.com/d1/platform/pricing/", "https://developers.cloudflare.com/queues/platform/pricing/", "https://developers.cloudflare.com/stream/pricing/", "https://developers.cloudflare.com/images/pricing/", "https://developers.cloudflare.com/realtime/sfu/pricing/", "https://developers.cloudflare.com/pages/functions/pricing/"),
  vercel: P("https://vercel.com/pricing", "https://vercel.com/docs/functions/usage-and-pricing", "https://vercel.com/docs/image-optimization/limits-and-pricing"),
  netlify: P("https://www.netlify.com/pricing/"),
  supabase: P("https://supabase.com/pricing"),
  deno: P("https://deno.com/deploy/pricing"),
  fastly: P("https://www.fastly.com/pricing"),
  heroku: P("https://www.heroku.com/pricing"),
  render: P("https://render.com/pricing"),
  railway: P("https://railway.com/pricing"),
  "fly-io": P("https://fly.io/docs/about/pricing/"),
  koyeb: P("https://www.koyeb.com/pricing"),
  northflank: P("https://northflank.com/pricing"),
  firebase: P("https://firebase.google.com/pricing"),
  github: P("https://github.com/pricing", "https://docs.github.com/en/billing/managing-billing-for-your-products/about-billing-for-github-actions"),
  appwrite: P("https://appwrite.io/pricing"),
  convex: P("https://www.convex.dev/pricing"),
  nhost: P("https://nhost.io/pricing"),
  coolify: P("https://coolify.io/pricing/"),
  // --- GPU
  lambda: P("https://lambda.ai/pricing"),
  runpod: P("https://www.runpod.io/pricing"),
  coreweave: P("https://www.coreweave.com/pricing"),
  "vast-ai": P("https://vast.ai/pricing"),
  modal: P("https://modal.com/pricing"),
  paperspace: P("https://www.paperspace.com/pricing"),
  replicate: P("https://replicate.com/pricing"),
  baseten: P("https://www.baseten.co/pricing/"),
  "hugging-face": P("https://huggingface.co/pricing"),
  // --- databases
  neon: P("https://neon.com/pricing"),
  planetscale: P("https://planetscale.com/pricing"),
  "crunchy-data": P("https://www.crunchydata.com/pricing"),
  aiven: P("https://aiven.io/pricing"),
  xata: P("https://xata.io/pricing"),
  tembo: P("https://tembo.io/pricing"),
  prisma: P("https://www.prisma.io/pricing"),
  tidb: P("https://www.pingcap.com/tidb-cloud-pricing-details/"),
  mongodb: P("https://www.mongodb.com/pricing"),
  couchbase: P("https://www.couchbase.com/pricing/"),
  ferretdb: P("https://www.ferretdb.com/pricing"),
  datastax: P("https://www.datastax.com/pricing/astra-db"),
  scylladb: P("https://www.scylladb.com/pricing/"),
  upstash: P("https://upstash.com/pricing", "https://upstash.com/pricing/qstash", "https://upstash.com/pricing/kafka"),
  cockroachdb: P("https://www.cockroachlabs.com/pricing/"),
  yugabytedb: P("https://www.yugabyte.com/pricing/"),
  singlestore: P("https://www.singlestore.com/pricing/"),
  turso: P("https://turso.tech/pricing"),
  bunny: P("https://bunny.net/pricing/", "https://bunny.net/pricing/stream/", "https://bunny.net/database/", "https://bunny.net/optimizer/"),
  neo4j: P("https://neo4j.com/pricing/"),
  arangodb: P("https://arangodb.com/pricing/"),
  tigergraph: P("https://www.tigergraph.com/pricing/"),
  memgraph: P("https://memgraph.com/pricing"),
  timescale: P("https://www.tigerdata.com/pricing"),
  influxdata: P("https://www.influxdata.com/influxdb-cloud-pricing/"),
  questdb: P("https://questdb.com/pricing/"),
  redis: P("https://redis.io/pricing/"),
  memcachier: P("https://www.memcachier.com/pricing"),
  // --- storage
  backblaze: P("https://www.backblaze.com/cloud-storage/pricing"),
  wasabi: P("https://wasabi.com/cloud-storage-pricing"),
  tigris: P("https://www.tigrisdata.com/pricing/"),
  veeam: P("https://www.veeam.com/products/veeam-data-platform/pricing.html"),
  rubrik: P("https://www.rubrik.com/products/pricing"),
  // --- network / edge
  akamai: P("https://www.akamai.com/products/content-delivery-network"),
  keycdn: P("https://www.keycdn.com/pricing"),
  cdn77: P("https://www.cdn77.com/pricing"),
  ns1: P("https://ns1.com/pricing"),
  kong: P("https://konghq.com/pricing"),
  zuplo: P("https://zuplo.com/pricing"),
  tyk: P("https://tyk.io/pricing/"),
  // --- messaging
  cloudamqp: P("https://www.cloudamqp.com/plans.html"),
  ably: P("https://ably.com/pricing"),
  pusher: P("https://pusher.com/channels/pricing/"),
  pubnub: P("https://www.pubnub.com/pricing/"),
  nats: P("https://www.synadia.com/cloud"),
  confluent: P("https://www.confluent.io/confluent-cloud/pricing/"),
  redpanda: P("https://www.redpanda.com/pricing"),
  temporal: P("https://temporal.io/pricing"),
  inngest: P("https://www.inngest.com/pricing"),
  "trigger-dev": P("https://trigger.dev/pricing"),
  astronomer: P("https://www.astronomer.io/pricing/"),
  prefect: P("https://www.prefect.io/pricing"),
  // --- email / sms / payments / comms
  sendgrid: P("https://sendgrid.com/en-us/pricing"),
  resend: P("https://resend.com/pricing"),
  postmark: P("https://postmarkapp.com/pricing"),
  mailgun: P("https://www.mailgun.com/pricing/"),
  brevo: P("https://www.brevo.com/pricing/"),
  twilio: P("https://www.twilio.com/en-us/sms/pricing/us", "https://www.twilio.com/en-us/video/pricing"),
  onesignal: P("https://onesignal.com/pricing"),
  messagebird: P("https://bird.com/en-us/pricing"),
  vonage: P("https://www.vonage.com/communications-apis/sms/pricing/"),
  meta: P("https://developers.facebook.com/docs/whatsapp/pricing/"),
  gupshup: P("https://www.gupshup.io/developer/pricing"),
  msg91: P("https://msg91.com/pricing"),
  stripe: P("https://stripe.com/pricing"),
  razorpay: P("https://razorpay.com/pricing/"),
  adyen: P("https://www.adyen.com/pricing"),
  paypal: P("https://www.paypal.com/us/business/paypal-business-fees"),
  paddle: P("https://www.paddle.com/pricing"),
  "lemon-squeezy": P("https://www.lemonsqueezy.com/pricing"),
  square: P("https://squareup.com/us/en/pricing"),
  cashfree: P("https://www.cashfree.com/payment-gateway-charges/"),
  phonepe: P("https://business.phonepe.com/pricing"),
  // --- data / analytics
  snowflake: P("https://www.snowflake.com/en/pricing-options/"),
  databricks: P("https://www.databricks.com/product/pricing", "https://www.databricks.com/product/pricing/databricks-sql"),
  clickhouse: P("https://clickhouse.com/pricing"),
  motherduck: P("https://motherduck.com/product/pricing/"),
  firebolt: P("https://www.firebolt.io/pricing"),
  tinybird: P("https://www.tinybird.co/pricing"),
  starburst: P("https://www.starburst.io/pricing/"),
  ververica: P("https://www.ververica.com/pricing"),
  decodable: P("https://www.decodable.co/pricing"),
  materialize: P("https://materialize.com/pricing/"),
  fivetran: P("https://www.fivetran.com/pricing"),
  airbyte: P("https://airbyte.com/pricing"),
  "dbt-labs": P("https://www.getdbt.com/pricing"),
  matillion: P("https://www.matillion.com/pricing"),
  estuary: P("https://estuary.dev/pricing/"),
  dremio: P("https://www.dremio.com/pricing/"),
  tableau: P("https://www.tableau.com/pricing/teams-orgs"),
  microsoft: P("https://www.microsoft.com/en-us/power-platform/products/power-bi/pricing"),
  metabase: P("https://www.metabase.com/pricing/"),
  preset: P("https://preset.io/pricing/"),
  hex: P("https://hex.tech/pricing/"),
  // --- search / vector
  elastic: P("https://www.elastic.co/pricing"),
  algolia: P("https://www.algolia.com/pricing"),
  typesense: P("https://cloud.typesense.org/pricing"),
  meilisearch: P("https://www.meilisearch.com/pricing"),
  pinecone: P("https://www.pinecone.io/pricing/"),
  qdrant: P("https://qdrant.tech/pricing/"),
  weaviate: P("https://weaviate.io/pricing"),
  zilliz: P("https://zilliz.com/pricing"),
  turbopuffer: P("https://turbopuffer.com/pricing"),
  chroma: P("https://www.trychroma.com/pricing"),
  // --- AI APIs
  openai: P("https://developers.openai.com/api/docs/pricing"),
  anthropic: P("https://platform.claude.com/docs/en/about-claude/pricing"),
  google: P("https://ai.google.dev/gemini-api/docs/pricing", "https://mapsplatform.google.com/pricing/"),
  mistral: P("https://mistral.ai/pricing#api-pricing"),
  cohere: P("https://cohere.com/pricing"),
  groq: P("https://groq.com/pricing"),
  "together-ai": P("https://www.together.ai/pricing"),
  "fireworks-ai": P("https://fireworks.ai/pricing"),
  deepseek: P("https://api-docs.deepseek.com/quick_start/pricing"),
  xai: P("https://docs.x.ai/docs/models"),
  openrouter: P("https://openrouter.ai/pricing"),
  "voyage-ai": P("https://docs.voyageai.com/docs/pricing"),
  jina: P("https://jina.ai/embeddings/"),
  deepgram: P("https://deepgram.com/pricing"),
  elevenlabs: P("https://elevenlabs.io/pricing/api"),
  assemblyai: P("https://www.assemblyai.com/pricing"),
  roboflow: P("https://roboflow.com/pricing"),
  "weights-biases": P("https://wandb.ai/site/pricing/"),
  // --- observability / dev tools
  datadog: P("https://www.datadoghq.com/pricing/"),
  grafana: P("https://grafana.com/pricing/"),
  "new-relic": P("https://newrelic.com/pricing"),
  dynatrace: P("https://www.dynatrace.com/pricing/"),
  splunk: P("https://www.splunk.com/en_us/products/pricing/platform-pricing.html"),
  "better-stack": P("https://betterstack.com/pricing"),
  axiom: P("https://axiom.co/pricing"),
  papertrail: P("https://www.papertrail.com/plans/"),
  honeycomb: P("https://www.honeycomb.io/pricing"),
  lightstep: P("https://docs.lightstep.com/docs/pricing"),
  sentry: P("https://sentry.io/pricing/"),
  rollbar: P("https://rollbar.com/pricing/"),
  bugsnag: P("https://www.bugsnag.com/pricing/"),
  highlight: P("https://www.highlight.io/pricing"),
  checkly: P("https://www.checklyhq.com/pricing/"),
  pingdom: P("https://www.pingdom.com/pricing/"),
  uptimerobot: P("https://uptimerobot.com/pricing/"),
  circleci: P("https://circleci.com/pricing/"),
  gitlab: P("https://about.gitlab.com/pricing/"),
  buildkite: P("https://buildkite.com/pricing/"),
  docker: P("https://www.docker.com/pricing/"),
  // --- identity / secrets / product tools
  auth0: P("https://auth0.com/pricing"),
  clerk: P("https://clerk.com/pricing"),
  workos: P("https://workos.com/pricing"),
  okta: P("https://www.okta.com/pricing/"),
  stytch: P("https://stytch.com/pricing"),
  ory: P("https://www.ory.sh/pricing"),
  hashicorp: P("https://www.hashicorp.com/en/products/vault/pricing"),
  doppler: P("https://www.doppler.com/pricing"),
  "1password": P("https://1password.com/developers/pricing/secrets-management"),
  infisical: P("https://infisical.com/pricing"),
  launchdarkly: P("https://launchdarkly.com/pricing/"),
  statsig: P("https://www.statsig.com/pricing"),
  posthog: P("https://posthog.com/pricing"),
  growthbook: P("https://www.growthbook.io/pricing"),
  flagsmith: P("https://www.flagsmith.com/pricing"),
  unleash: P("https://www.getunleash.io/pricing"),
  amplitude: P("https://amplitude.com/pricing"),
  mixpanel: P("https://mixpanel.com/pricing/"),
  segment: P("https://segment.com/pricing/"),
  plausible: P("https://plausible.io/#pricing"),
  heap: P("https://www.heap.io/pricing"),
  rudderstack: P("https://www.rudderstack.com/pricing/"),
  contentful: P("https://www.contentful.com/pricing/"),
  sanity: P("https://www.sanity.io/pricing"),
  strapi: P("https://strapi.io/pricing-cloud"),
  storyblok: P("https://www.storyblok.com/pricing"),
  hygraph: P("https://hygraph.com/pricing"),
  payload: P("https://payloadcms.com/pricing"),
  // --- media / maps / realtime
  mux: P("https://www.mux.com/pricing"),
  vimeo: P("https://vimeo.com/enterprise/pricing"),
  "api-video": P("https://api.video/pricing/"),
  cloudinary: P("https://cloudinary.com/pricing"),
  imgix: P("https://imgix.com/pricing"),
  imagekit: P("https://imagekit.io/plans/"),
  mapbox: P("https://www.mapbox.com/pricing"),
  here: P("https://www.here.com/get-started/pricing"),
  maptiler: P("https://www.maptiler.com/cloud/pricing/"),
  livekit: P("https://livekit.io/pricing"),
  daily: P("https://www.daily.co/pricing/"),
  agora: P("https://www.agora.io/en/pricing/"),
  zoom: P("https://www.zoom.com/en/developer-pricing/"),
  stream: P("https://getstream.io/chat/pricing/"),
  sendbird: P("https://sendbird.com/pricing"),
  hivemq: P("https://www.hivemq.com/pricing/"),
  emqx: P("https://www.emqx.com/en/pricing"),
  particle: P("https://www.particle.io/pricing/"),
};

/** Open-source / self-hosted software: no licence fee, you pay for the server it runs on. */
export const FREE_SOFTWARE = ["nginx", "caddy", "traefik", "haproxy", "jenkins", "keycloak", "debezium", "jaeger", "litestream", "pocketbase", "rabbitmq", "uptime-kuma"];
